version: '3.8'

services:
  redis:
    image: redis:alpine
    volumes:
      - redis-data:/data

  web:
    build: .
    ports:
      - "8000:5000"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  redis-data: